# Generated by Django 3.1.2 on 2020-10-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
