# Generated by Django 3.1.1 on 2020-10-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201017_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=20)),
                ('regulation', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
