# Generated by Django 3.1.1 on 2020-10-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201020_1036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PdfUploads',
            new_name='PdfUpload',
        ),
    ]
