# Generated by Django 3.1.1 on 2020-10-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201020_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='pdf_file',
            field=models.FileField(max_length=200, upload_to='pdfs/'),
        ),
    ]
